#作者:邓智豪
obj = main.cpp ../Utils/scanFormatInput.cpp ../Utils/formatOutput.cpp ../Algorithm/crossover.cpp ../Algorithm/describeTable.cpp ../Algorithm/gene.cpp ../Algorithm/mutate.cpp ../Algorithm/decode.cpp ../Algorithm/index.cpp

main: $(obj)
	g++ -o main $(obj)
