#作者:邓智豪
obj = main.c ./scanFormatInput.c ./formatOutput.c ../Algorithm/crossover.c ../Algorithm/describeTable.c ../Algorithm/gene.c ../Algorithm/mutate.c ../Algorithm/decode.c

main: $(obj)
	gcc -o main $(obj)
