#作者:邓智豪
obj = overall.c ../CLI/scanFormatInput.c ../CLI/formatOutput.c ../Algorithm/crossover.c ../Algorithm/describeTable.c ../Algorithm/gene.c ../Algorithm/mutate.c ../Algorithm/decode.c

test: $(obj)
	gcc -o test $(obj)
